channels:
  - defaults
dependencies:
  - scikit-learn
  - jupyter
  - spacy
  - lxml
  - nltk
  - pylint
  - matplotlib
  - pandas
  - numpy
  - pytest
  - yaml
  - pip
  - autopep8
  - gensim
  - pip:
    - pyLDAvis 
