channels:
  - defaults
dependencies:
  - jupyter
  - spacy
  - yaml
  - pandas
  - pylint
  - matplotlib
  - lxml
  - gensim
  - scikit-learn
  - pip
  - autopep8
  - nltk
  - numpy
  - pytest
  - pyyaml
  - pdoc3
  - geopandas
  - pip:
    - pyLDAvis
    - json_lines
    - yaml
    - wordcloud
    - textblob
    - shapely
